# qt_add_executable(backend_app main.cpp)

# target_link_libraries(backend_app PRIVATE
#     Qt6::Core
#     Qt6::Quick
#     Qt6::Qml
# )

# target_sources(backend_app PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../frontend/resources.qrc)

# # Set QML import path for the executable
# set_target_properties(backend_app PROPERTIES QT_QML_IMPORT_PATH "${CMAKE_BINARY_DIR}/frontend")
